In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)
!ls "/content/drive/My Drive/languages"

Mounted at /content/drive
'Language Detection.csv'


In [2]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter("ignore")

In [3]:
data = pd.read_csv("/content/drive/My Drive/languages/Language Detection.csv")

In [4]:
data

Text Language
0       Nature, in the broadest sense, is the natural...  English
1      "Nature" can refer to the phenomena of the phy...  English
2      The study of nature is a large, if not the onl...  English
3      Although humans are part of nature, human acti...  English
4      [1] The word nature is borrowed from the Old F...  English
...                                                  ...      ...
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

[10337 rows x 2 columns]

In [5]:
data['Language'].value_counts()

English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: Language, dtype: int64

In [6]:
X = data['Text']
Y = data['Language']

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)


In [8]:
y

array([3, 3, 3, ..., 9, 9, 9])

In [9]:
data_list=[]
for i in X:
  i = re.sub(r'[!@#$(),n"%^*?:;~`0-9]', ' ', i)
  i = re.sub(r'[[]]', ' ', i)
  i = i.lower()
  data_list.append(i)

In [10]:
data_list

[' nature  i  the broadest se se  is the  atural  physical  material world or u iverse.',
 ' nature  ca  refer to the phe ome a of the physical world  a d also to life i  ge eral.',
 'the study of  ature is a large  if  ot the o ly  part of scie ce.',
 'although huma s are part of  ature  huma  activity is ofte  u derstood as a separate category from other  atural phe ome a.',
 '[ ] the word  ature is borrowed from the old fre ch  ature a d is derived from the lati  word  atura  or  esse tial qualities  i  ate dispositio    a d i  a cie t times  literally mea t  birth .',
 '[ ] i  a cie t philosophy   atura is mostly used as the lati  tra slatio  of the greek word physis  φύσις   which origi ally related to the i tri sic characteristics that pla ts  a imals  a d other features of the world develop of their ow  accord.',
 '[ ][ ] \nthe co cept of  ature as a whole  the physical u iverse  is o e of several expa sio s of the origi al  otio  [ ] it bega  with certai  core applicatio s of t

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(data_list).toarray()
X.shape

(10337, 34937)

In [12]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size =0.20)

In [14]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [15]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 50)
clf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [16]:
y_pred = model.predict(x_test)

In [17]:
y_pred1 = clf.predict(x_test)

In [18]:
y_pred

array([14,  3,  3, ..., 12, 13,  2])

In [19]:
y_pred1

array([14,  3,  3, ..., 12, 13, 13])

In [20]:
y_test

array([14,  3,  3, ..., 12, 13,  2])

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)

In [22]:
ac1 = accuracy_score(y_test,y_pred1)
ac1

0.9221470019342359

In [23]:
ac

0.9738878143133463

In [24]:
cm

array([[ 93,   0,   0,   3,   0,   0,   0,   0,   0,   0,   2,   0,   0,
          0,   0,   0,   0],
       [  0,  79,   0,   1,   1,   0,   0,   0,   0,   0,   0,   1,   0,
          0,   2,   0,   0],
       [  0,   0, 109,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   0,   0,   0],
       [  0,   0,   0, 256,   0,   1,   0,   0,   1,   0,   0,   0,   0,
          0,   0,   0,   0],
       [  0,   0,   0,   1, 184,   0,   0,   0,   1,   0,   0,   0,   0,
          0,   0,   0,   0],
       [  0,   0,   0,   1,   0,  97,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  72,   0,   0,   0,   1,   0,   0,
          0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  13,   0,   0,   0,   0,   0,
          0,   0,   0,   0],
       [  0,   0,   1,   1,   0,   0,   0,   0, 118,   0,   0,   0,   0,
          0,   0,   0,   0],
       [  0,   0,   0,   3,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         

In [25]:
def predict(text):
  x = cv.transform([text]).toarray()
  lang = model.predict(x)
  lang = le.inverse_transform(lang)
  print(lang[0])

In [26]:
keyword = input("Enter the sentence : ") 
predict(str(keyword))

Enter the sentence : "Analytics Vidhya - это портал знаний на базе сообщества для профессионалов в области аналитики и данных."
Russian


In [ ]:
predict("അനലിറ്റിക്സ്, ഡാറ്റാ സയൻസ് പ്രൊഫഷണലുകൾക്കായി കമ്മ്യൂണിറ്റി അധിഷ്ഠിത വിജ്ഞാന പോർട്ടൽ അനലിറ്റിക്സ് വിദ്യ നൽകുന്നു")

Malayalam


In [ ]:
predict("समझे कि नहीं")

Hindi


In [ ]:
predict("la casa de papal")

Spanish
